In [1]:
# Importing necessary libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

### EA Dataset

In [2]:
df_ea = pd.read_excel("C:/Users/Lenovo/Desktop/21112341_Datasets.xlsx")

In [3]:
df_ea

,S.No.,Dataset,Link,Type,Possible Analysis/Analytics,Date of creation,Any projects
0,1,Inflation,https://datahub.io/core/inflation,Time series,Inflationary trend from 1973 - 2016 of a count...,2018,NaN
1,2,Population,https://datahub.io/core/population,Time series,Change in population from 1960-2018 of a count...,2020,NaN
2,3,Bank of England Interest Rates,https://datahub.io/core/interest-rates-gb,Numerical,Interest trends of England from 1694 - 2016,2018,NaN
3,4,Population and unemployment,https://github.com/selva86/datasets/blob/maste...,Time series,Population and unemployment trends from 1967 -...,2016,NaN
4,5,IBRD Subscriptions and voting power of Member ...,https://finances.worldbank.org/Shareholder-Equ...,Time series,"Total capital subscribed, Total capital paid, ...",2022,NaN
5,6,Exchange Rates,https://datahub.io/core/exchange-rates,Time series,Exchange rate trends of different countries fr...,2018,NaN
6,7,UK govt bond yiels,https://datahub.io/core/bond-yields-uk-10y,Time series,average yield from british govt. securities fr...,2020,NaN
7,8,USA Education Budget,https://datahub.io/core/usa-education-budget-a...,Time series,"Budget spent by USA on education, USA Budget e...",2018,NaN
8,9,Gross Capital formation (% of GDP),https://data.worldbank.org/indicator/NE.GDI.TO...,Time series,Gross capital formation of different countries,2022,NaN
9,10,UK trade in goods,https://www.ons.gov.uk/economy/nationalaccount...,Time series,"Annual, monthly and quartely trade of goods f...",2022,NaN
10,11,Output of production industries,https://www.ons.gov.uk/economy/economicoutputa...,Time series,% change in the production output of main indu...,2022,NaN
11,12,State - wise socio economic indicators,https://data.opencity.in/dataset/statewise-soc...,Numerical,Best socio economic indicators out of all the ...,2022,NaN
12,13,Unemployment in India,https://www.kaggle.com/datasets/gokulrajkmv/un...,Time series,How unemployment rate increased during Covid 19,2021,NaN
13,14,US local area unemp. Statistics,https://catalog.data.gov/dataset/local-area-un...,Time series,Employment and unemployment rate 1976 - 2022 i...,2022,NaN
14,15,India GDP from 1960-2021,https://www.macrotrends.net/countries/IND/indi...,Time series,Comparision of growth and annual percentage of...,2022,NaN

In [4]:
#Renaming the columns

df_ea.rename(columns = {'Possible Analysis/Analytics':'Focus'}, inplace = True)
df_ea.rename(columns = {'Date of creation':'Date'}, inplace = True)
df_ea.rename(columns = {'Any projects':'Project_Title'}, inplace = True)
df_ea.rename(columns = {'Link':'DS_Link'}, inplace = True)

In [5]:
#Inserting a new column

Analyst_RegNo = 21112341
df_ea.insert(loc = 1, column = 'Analyst Regpister Number', value = Analyst_RegNo)

In [6]:
#Null values

df_ea['Project_Title'] = df_ea['Project_Title'].fillna('None')

In [7]:
#Removing a column

df_ea = df_ea.drop(df_ea.columns[0], axis = 1)
df_ea.index.names = ['Serial Number']

In [ ]:
# Replacing a column to a certain position

def moveColumn(df, column_name, position):
    column_to_move = df.pop(column_name)
    df.insert(position, column_name, column_to_move)

moveColumn(df, 'Rent', 13)

In [8]:
df_ea

,Analyst Register Number,Dataset,DS_Link,Type,Focus,Date,Project_Title
Serial Number,,,,,,,
0,21112341,Inflation,https://datahub.io/core/inflation,Time series,Inflationary trend from 1973 - 2016 of a count...,2018,None
1,21112341,Population,https://datahub.io/core/population,Time series,Change in population from 1960-2018 of a count...,2020,None
2,21112341,Bank of England Interest Rates,https://datahub.io/core/interest-rates-gb,Numerical,Interest trends of England from 1694 - 2016,2018,None
3,21112341,Population and unemployment,https://github.com/selva86/datasets/blob/maste...,Time series,Population and unemployment trends from 1967 -...,2016,None
4,21112341,IBRD Subscriptions and voting power of Member ...,https://finances.worldbank.org/Shareholder-Equ...,Time series,"Total capital subscribed, Total capital paid, ...",2022,None
5,21112341,Exchange Rates,https://datahub.io/core/exchange-rates,Time series,Exchange rate trends of different countries fr...,2018,None
6,21112341,UK govt bond yiels,https://datahub.io/core/bond-yields-uk-10y,Time series,average yield from british govt. securities fr...,2020,None
7,21112341,USA Education Budget,https://datahub.io/core/usa-education-budget-a...,Time series,"Budget spent by USA on education, USA Budget e...",2018,None
8,21112341,Gross Capital formation (% of GDP),https://data.worldbank.org/indicator/NE.GDI.TO...,Time series,Gross capital formation of different countries,2022,None
9,21112341,UK trade in goods,https://www.ons.gov.uk/economy/nationalaccount...,Time series,"Annual, monthly and quartely trade of goods f...",2022,None
10,21112341,Output of production industries,https://www.ons.gov.uk/economy/economicoutputa...,Time series,% change in the production output of main indu...,2022,None
11,21112341,State - wise socio economic indicators,https://data.opencity.in/dataset/statewise-soc...,Numerical,Best socio economic indicators out of all the ...,2022,None
12,21112341,Unemployment in India,https://www.kaggle.com/datasets/gokulrajkmv/un...,Time series,How unemployment rate increased during Covid 19,2021,None
13,21112341,US local area unemp. Statistics,https://catalog.data.gov/dataset/local-area-un...,Time series,Employment and unemployment rate 1976 - 2022 i...,2022,None
14,21112341,India GDP from 1960-2021,https://www.macrotrends.net/countries/IND/indi...,Time series,Comparision of growth and annual percentage of...,2022,None

### DS Dataset

In [9]:
df_ds1 = pd.read_excel("C:/Users/Lenovo/Downloads/21112016_KrishAgarwal_TypesOfAnalysis (1).xlsx")

In [10]:
df_ds1

,Sr No.,Project Title,Major Focus,Source,Dataset,DS Source
0,1,ad hoc reporting,"Business Intelligence, Data Wrangling, Visuali...",https://www.oracle.com/in/business-analytics/d...,Financial Reporting,https://www.datarails.com/financial-reports/
1,2,Sentiment Analysis,"NLP, Regex, Text Analysis,",https://www.jigsawacademy.com/blogs/business-a...,Twitter Sentimetn Analysis,https://www.kaggle.com/datasets/jp797498e/twit...
2,3,Forecasting,"Regression, Time Series, Qualitative",https://medium.com/@joseph.magiya/introduction...,Store Sales,https://www.kaggle.com/competitions/store-sale...
3,4,Customer Segmentation,"Correlation, Clustering, KNN",https://www.optimove.com/resources/learning-ce...,Customer Segmentation,https://www.kaggle.com/code/fabiendaniel/custo...
4,5,Music Recommendation Engine,"Content-based filtering, collaborative filteri...",https://www.music-tomorrow.com/blog/how-spotif...,Spotify Dataset,https://www.kaggle.com/code/vatsalmavani/music...
5,6,Detection of Global Suicide Rates,EDA,https://medium.com/analytics-vidhya/data-analy...,Suicide Rates Overview 1985 to 2016,https://www.kaggle.com/datasets/russellyates88...
6,7,Sports Data Analysis,"Exploration, Visualization, Correlation, Predi...",https://www.youtube.com/watch?v=MpLHMKTolVw,Sports Data,https://www.kaggle.com/general/63590
7,8,Pollution Analysis,"Analytical Chemistry, Liquid Chromatography",https://pubmed.ncbi.nlm.nih.gov/9155775/,Air Quality Data in India (2015 - 2020),https://www.kaggle.com/datasets/rohanrao/air-q...
8,9,Solar Eclipse Prediction,"Time Series Analysis, Pattern Recognition,",https://www.atlasobscura.com/articles/how-to-p...,Solar and Lunar Eclipses,https://www.kaggle.com/datasets/nasa/solar-ecl...
9,10,Wine Quality Prediction,"Random Forest Classifier, Stochastic Gradient ...",https://www.springboard.com/blog/data-analytic...,Wine Quality Dataset,https://www.kaggle.com/datasets/yasserh/wine-q...
10,11,Breast Cancer Classification,"CNN, Classification",https://www.analyticsvidhya.com/blog/2021/06/b...,Breast Cancer Wisconsin (Diagnostic) Data Set,https://www.kaggle.com/datasets/uciml/breast-c...
11,12,Anomaly Detection for Trustworthy Services in ...,"SVDD, Time Series Analysis",https://www.researchgate.net/publication/31729...,IEEE,https://ieeexplore.ieee.org/document/7937930
12,13,Sales Strategy Optimization,"AI, Web Traffic analysis, Campaign Tracking, R...",https://www.setsail.co/blog/sales-optimization...,Price optimization for e-commerce: a case study,https://tryolabs.com/blog/2020/06/01/price-opt...
13,14,Supply Chain Analytics,"Descriptive Analytics, Predictive Analytics, P...",https://www.netsuite.com/portal/resource/artic...,Supply Chain Shipment Pricing,https://data.world/usaid/supply-chain-shipment...
14,15,Traffic Analysis,"Time Series Analysis, Geographical Analysis",https://www.netreo.com/blog/how-to-analyze-net...,Traffic Prediction Dataset,https://www.kaggle.com/datasets/fedesoriano/tr...
15,16,Random Matrix theory Framework in a Non-Gaussi...,"Random Matrix Theory, Time Series Analysis",https://ieeexplore.ieee.org/stamp/stamp.jsp?ar...,IEEE,https://ieeexplore.ieee.org/stamp/stamp.jsp?ar...
16,17,Mountaineering Events Using Provable Secure Pr...,"Clustering, Data Fusion, Comprehensive Analysis",https://ieeexplore.ieee.org/stamp/stamp.jsp?ar...,IEEE,https://ieeexplore.ieee.org/stamp/stamp.jsp?ar...
17,18,NaN,NaN,NaN,NaN,NaN
18,19,NaN,NaN,NaN,NaN,NaN
19,20,NaN,NaN,NaN,NaN,NaN

In [11]:
#Removing a column

df_ds1 = df_ds1.drop(df_ds1.columns[0], axis = 1)
df_ds1 = df_ds1.drop([17, 18, 19])
df_ds1.index.names = ['Serial Number']

In [12]:
#Inserting a new column

Analyst_RegNo = 21112016
df_ds1.insert(loc = 0, column = 'Analyst Register Number', value = Analyst_RegNo)

In [13]:
#Renaming the columns

df_ds1.rename(columns = {'Major Focus':'Focus'}, inplace = True)
df_ds1.rename(columns = {'Source':'Project_Source'}, inplace = True)
df_ds1.rename(columns = {'DS Source':'DS_Link'}, inplace = True)

In [14]:
df_ds1

,Analyst Register Number,Project Title,Focus,Project_Source,Dataset,DS_Link
Serial Number,,,,,,
0,21112016,ad hoc reporting,"Business Intelligence, Data Wrangling, Visuali...",https://www.oracle.com/in/business-analytics/d...,Financial Reporting,https://www.datarails.com/financial-reports/
1,21112016,Sentiment Analysis,"NLP, Regex, Text Analysis,",https://www.jigsawacademy.com/blogs/business-a...,Twitter Sentimetn Analysis,https://www.kaggle.com/datasets/jp797498e/twit...
2,21112016,Forecasting,"Regression, Time Series, Qualitative",https://medium.com/@joseph.magiya/introduction...,Store Sales,https://www.kaggle.com/competitions/store-sale...
3,21112016,Customer Segmentation,"Correlation, Clustering, KNN",https://www.optimove.com/resources/learning-ce...,Customer Segmentation,https://www.kaggle.com/code/fabiendaniel/custo...
4,21112016,Music Recommendation Engine,"Content-based filtering, collaborative filteri...",https://www.music-tomorrow.com/blog/how-spotif...,Spotify Dataset,https://www.kaggle.com/code/vatsalmavani/music...
5,21112016,Detection of Global Suicide Rates,EDA,https://medium.com/analytics-vidhya/data-analy...,Suicide Rates Overview 1985 to 2016,https://www.kaggle.com/datasets/russellyates88...
6,21112016,Sports Data Analysis,"Exploration, Visualization, Correlation, Predi...",https://www.youtube.com/watch?v=MpLHMKTolVw,Sports Data,https://www.kaggle.com/general/63590
7,21112016,Pollution Analysis,"Analytical Chemistry, Liquid Chromatography",https://pubmed.ncbi.nlm.nih.gov/9155775/,Air Quality Data in India (2015 - 2020),https://www.kaggle.com/datasets/rohanrao/air-q...
8,21112016,Solar Eclipse Prediction,"Time Series Analysis, Pattern Recognition,",https://www.atlasobscura.com/articles/how-to-p...,Solar and Lunar Eclipses,https://www.kaggle.com/datasets/nasa/solar-ecl...
9,21112016,Wine Quality Prediction,"Random Forest Classifier, Stochastic Gradient ...",https://www.springboard.com/blog/data-analytic...,Wine Quality Dataset,https://www.kaggle.com/datasets/yasserh/wine-q...
10,21112016,Breast Cancer Classification,"CNN, Classification",https://www.analyticsvidhya.com/blog/2021/06/b...,Breast Cancer Wisconsin (Diagnostic) Data Set,https://www.kaggle.com/datasets/uciml/breast-c...
11,21112016,Anomaly Detection for Trustworthy Services in ...,"SVDD, Time Series Analysis",https://www.researchgate.net/publication/31729...,IEEE,https://ieeexplore.ieee.org/document/7937930
12,21112016,Sales Strategy Optimization,"AI, Web Traffic analysis, Campaign Tracking, R...",https://www.setsail.co/blog/sales-optimization...,Price optimization for e-commerce: a case study,https://tryolabs.com/blog/2020/06/01/price-opt...
13,21112016,Supply Chain Analytics,"Descriptive Analytics, Predictive Analytics, P...",https://www.netsuite.com/portal/resource/artic...,Supply Chain Shipment Pricing,https://data.world/usaid/supply-chain-shipment...
14,21112016,Traffic Analysis,"Time Series Analysis, Geographical Analysis",https://www.netreo.com/blog/how-to-analyze-net...,Traffic Prediction Dataset,https://www.kaggle.com/datasets/fedesoriano/tr...
15,21112016,Random Matrix theory Framework in a Non-Gaussi...,"Random Matrix Theory, Time Series Analysis",https://ieeexplore.ieee.org/stamp/stamp.jsp?ar...,IEEE,https://ieeexplore.ieee.org/stamp/stamp.jsp?ar...
16,21112016,Mountaineering Events Using Provable Secure Pr...,"Clustering, Data Fusion, Comprehensive Analysis",https://ieeexplore.ieee.org/stamp/stamp.jsp?ar...,IEEE,https://ieeexplore.ieee.org/stamp/stamp.jsp?ar...

### DS Dataset

In [15]:
df_ds2 = pd.read_excel("C:/Users/Lenovo/Downloads/21112009_DataAnalyticsProjects (1).xlsx", header = 1)

In [16]:
#Removing a column

df_ds2 = df_ds2.drop(df_ds2.columns[0], axis = 1)
df_ds2.index.names = ['Serial Number']

In [17]:
#Inserting a new column

Analyst_RegNo = 21112009
df_ds2.insert(loc = 0, column = 'Analyst Register Number', value = Analyst_RegNo)

In [18]:
df_ds2.head()

,Analyst Register Number,Project title,Major focus,Source,Data set,DataSet source
Serial Number,,,,,,
0,21112009,Diamond Price Analysis,"ML, financial analysis, price analysis",https://thecleverprogrammer.com/2022/09/26/dia...,Diamonds,https://www.kaggle.com/datasets/shivam2503/dia...
1,21112009,Water Quality Analysis,"Prediction, relationship, ML model",https://thecleverprogrammer.com/2021/08/19/wat...,water_potability.csv,https://raw.githubusercontent.com/amankharwal/...
2,21112009,Gender Pay Gap Analysis,Financial analysis,https://www.interviewquery.com/p/data-analytic...,Median Weekly Earnings by Sex,https://data.world/bls/median-weekly-earnings-...
3,21112009,Uber Trip Analysis,Visual analysis,https://www.interviewquery.com/p/data-analytic...,Uber Pickups in New York City\n,https://www.kaggle.com/datasets/fivethirtyeigh...
4,21112009,Breast Cancer Classification,Naive Bayes Algorithm in machine learning,https://www.askpython.com/python/data-science-...,Breast Cancer Classification,https://www.kaggle.com/niteshyadav3103/breast-...

In [19]:
df_ds2.rename(columns = {'Project title ':'Project Title'}, inplace = True)
df_ds2.rename(columns = {'Major focus ':'Focus'}, inplace = True)
df_ds2.rename(columns = {'Source ':'Project Source'}, inplace = True)
df_ds2.rename(columns = {'Data set ':'Dataset'}, inplace = True)
df_ds2.rename(columns = {'DataSet source':'DS_Link'}, inplace = True)

In [20]:
df_ds2.head()

,Analyst Register Number,Project Title,Focus,Project Source,Dataset,DS_Link
Serial Number,,,,,,
0,21112009,Diamond Price Analysis,"ML, financial analysis, price analysis",https://thecleverprogrammer.com/2022/09/26/dia...,Diamonds,https://www.kaggle.com/datasets/shivam2503/dia...
1,21112009,Water Quality Analysis,"Prediction, relationship, ML model",https://thecleverprogrammer.com/2021/08/19/wat...,water_potability.csv,https://raw.githubusercontent.com/amankharwal/...
2,21112009,Gender Pay Gap Analysis,Financial analysis,https://www.interviewquery.com/p/data-analytic...,Median Weekly Earnings by Sex,https://data.world/bls/median-weekly-earnings-...
3,21112009,Uber Trip Analysis,Visual analysis,https://www.interviewquery.com/p/data-analytic...,Uber Pickups in New York City\n,https://www.kaggle.com/datasets/fivethirtyeigh...
4,21112009,Breast Cancer Classification,Naive Bayes Algorithm in machine learning,https://www.askpython.com/python/data-science-...,Breast Cancer Classification,https://www.kaggle.com/niteshyadav3103/breast-...

### Merging Dataset

In [21]:
df = pd.concat([df_ea, df_ds1, df_ds2], axis = 0)

In [22]:
df

,Analyst Register Number,Dataset,DS_Link,Type,Focus,Date,Project_Title,Project Title,Project_Source,Project Source
Serial Number,,,,,,,,,,
0,21112341,Inflation,https://datahub.io/core/inflation,Time series,Inflationary trend from 1973 - 2016 of a count...,2018.0,None,NaN,NaN,NaN
1,21112341,Population,https://datahub.io/core/population,Time series,Change in population from 1960-2018 of a count...,2020.0,None,NaN,NaN,NaN
2,21112341,Bank of England Interest Rates,https://datahub.io/core/interest-rates-gb,Numerical,Interest trends of England from 1694 - 2016,2018.0,None,NaN,NaN,NaN
3,21112341,Population and unemployment,https://github.com/selva86/datasets/blob/maste...,Time series,Population and unemployment trends from 1967 -...,2016.0,None,NaN,NaN,NaN
4,21112341,IBRD Subscriptions and voting power of Member ...,https://finances.worldbank.org/Shareholder-Equ...,Time series,"Total capital subscribed, Total capital paid, ...",2022.0,None,NaN,NaN,NaN
5,21112341,Exchange Rates,https://datahub.io/core/exchange-rates,Time series,Exchange rate trends of different countries fr...,2018.0,None,NaN,NaN,NaN
6,21112341,UK govt bond yiels,https://datahub.io/core/bond-yields-uk-10y,Time series,average yield from british govt. securities fr...,2020.0,None,NaN,NaN,NaN
7,21112341,USA Education Budget,https://datahub.io/core/usa-education-budget-a...,Time series,"Budget spent by USA on education, USA Budget e...",2018.0,None,NaN,NaN,NaN
8,21112341,Gross Capital formation (% of GDP),https://data.worldbank.org/indicator/NE.GDI.TO...,Time series,Gross capital formation of different countries,2022.0,None,NaN,NaN,NaN
9,21112341,UK trade in goods,https://www.ons.gov.uk/economy/nationalaccount...,Time series,"Annual, monthly and quartely trade of goods f...",2022.0,None,NaN,NaN,NaN
10,21112341,Output of production industries,https://www.ons.gov.uk/economy/economicoutputa...,Time series,% change in the production output of main indu...,2022.0,None,NaN,NaN,NaN
11,21112341,State - wise socio economic indicators,https://data.opencity.in/dataset/statewise-soc...,Numerical,Best socio economic indicators out of all the ...,2022.0,None,NaN,NaN,NaN
12,21112341,Unemployment in India,https://www.kaggle.com/datasets/gokulrajkmv/un...,Time series,How unemployment rate increased during Covid 19,2021.0,None,NaN,NaN,NaN
13,21112341,US local area unemp. Statistics,https://catalog.data.gov/dataset/local-area-un...,Time series,Employment and unemployment rate 1976 - 2022 i...,2022.0,None,NaN,NaN,NaN
14,21112341,India GDP from 1960-2021,https://www.macrotrends.net/countries/IND/indi...,Time series,Comparision of growth and annual percentage of...,2022.0,None,NaN,NaN,NaN
0,21112016,Financial Reporting,https://www.datarails.com/financial-reports/,NaN,"Business Intelligence, Data Wrangling, Visuali...",NaN,NaN,ad hoc reporting,https://www.oracle.com/in/business-analytics/d...,NaN
1,21112016,Twitter Sentimetn Analysis,https://www.kaggle.com/datasets/jp797498e/twit...,NaN,"NLP, Regex, Text Analysis,",NaN,NaN,Sentiment Analysis,https://www.jigsawacademy.com/blogs/business-a...,NaN
2,21112016,Store Sales,https://www.kaggle.com/competitions/store-sale...,NaN,"Regression, Time Series, Qualitative",NaN,NaN,Forecasting,https://medium.com/@joseph.magiya/introduction...,NaN
3,21112016,Customer Segmentation,https://www.kaggle.com/code/fabiendaniel/custo...,NaN,"Correlation, Clustering, KNN",NaN,NaN,Customer Segmentation,https://www.optimove.com/resources/learning-ce...,NaN
4,21112016,Spotify Dataset,https://www.kaggle.com/code/vatsalmavani/music...,NaN,"Content-based filtering, collaborative filteri...",NaN,NaN,Music Recommendation Engine,https://www.music-tomorrow.com/blog/how-spotif...,NaN
5,21112016,Suicide Rates Overview 1985 to 2016,https://www.kaggle.com/datasets/russellyates88...,NaN,EDA,NaN,NaN,Detection of Global Suicide Rates,https://medium.com/analytics-vidhya/data-analy...,NaN
6,21112016,Sports Data,https://www.kaggle.com/general/63590,NaN,"Exploration, Visualization, Correlation, Predi...",NaN,NaN,Sports Data Analysis,https://www.youtube.com/watch?v=MpLHMKTolVw,NaN
7,21112016,Air Quality Data in India (2015 - 2020),https://www.kaggle.com/datasets/rohanrao/air-q...,NaN,"Analytical Chemistry, Liquid Chromatography",NaN,NaN,Pollution Analysis,https://pubmed.ncbi.nlm.nih.gov/9155775/,NaN
8,21112016,Solar and Lunar Eclipses,https://www.kaggle.com/datasets/nasa/solar-ecl...,NaN,"Time Series Analysis, Pattern Recognition,",NaN,NaN,Solar Eclipse Prediction,https://www.atlasobscura.com/articles/how-to-p...,NaN
9,21112016,Wine Quality Dataset,https://www.kaggle.com/datasets/yasserh/wine-q...,NaN,"Random Forest Classifier, Stochastic Gradient ...",NaN,NaN,Wine Quality Prediction,https://www.springboard.com/blog/data-analytic...,NaN
10,21112016,Breast Cancer Wisconsin (Diagnostic) Data Set,https://www.kaggle.com/datasets/uciml/breast-c...,NaN,"CNN, Classification",NaN,NaN,Breast Cancer Classification,https://www.analyticsvidhya.com/blog/2021/06/b...,NaN
11,21112016,IEEE,https://ieeexplore.ieee.org/document/7937930,NaN,"SVDD, Time Series Analysis",NaN,NaN,Anomaly Detection for Trustworthy Services in ...,https://www.researchgate.net/publication/31729...,NaN
12,21112016,Price optimization for e-commerce: a case study,https://tryolabs.com/blog/2020/06/01/price-opt...,NaN,"AI, Web Traffic analysis, Campaign Tracking, R...",NaN,NaN,Sales Strategy Optimization,https://www.setsail.co/blog/sales-optimization...,NaN
13,21112016,Supply Chain Shipment Pricing,https://data.world/usaid/supply-chain-shipment...,NaN,"Descriptive Analytics, Predictive Analytics, P...",NaN,NaN,Supply Chain Analytics,https://www.netsuite.com/portal/resource/artic...,NaN
14,21112016,Traffic Prediction Dataset,https://www.kaggle.com/datasets/fedesoriano/tr...,NaN,"Time Series Analysis, Geographical Analysis",NaN,NaN,Traffic Analysis,https://www.netreo.com/blog/how-to-analyze-net...,NaN
15,21112016,IEEE,https://ieeexplore.ieee.org/stamp/stamp.jsp?ar...,NaN,"Random Matrix Theory, Time Series Analysis",NaN,NaN,Random Matrix theory Framework in a Non-Gaussi...,https://ieeexplore.ieee.org/stamp/stamp.jsp?ar...,NaN
16,21112016,IEEE,https://ieeexplore.ieee.org/stamp/stamp.jsp?ar...,NaN,"Clustering, Data Fusion, Comprehensive Analysis",NaN,NaN,Mountaineering Events Using Provable Secure Pr...,https://ieeexplore.ieee.org/stamp/stamp.jsp?ar...,NaN
0,21112009,Diamonds,https://www.kaggle.com/datasets/shivam2503/dia...,NaN,"ML, financial analysis, price analysis",NaN,NaN,Diamond Price Analysis,NaN,https://thecleverprogrammer.com/2022/09/26/dia...
1,21112009,water_potability.csv,https://raw.githubusercontent.com/amankharwal/...,NaN,"Prediction, relationship, ML model",NaN,NaN,Water Quality Analysis,NaN,https://thecleverprogrammer.com/2021/08/19/wat...
2,21112009,Median Weekly Earnings by Sex,https://data.world/bls/median-weekly-earnings-...,NaN,Financial analysis,NaN,NaN,Gender Pay Gap Analysis,NaN,https://www.interviewquery.com/p/data-analytic...
3,21112009,Uber Pickups in New York City\n,https://www.kaggle.com/datasets/fivethirtyeigh...,NaN,Visual analysis,NaN,NaN,Uber Trip Analysis,NaN,https://www.interviewquery.com/p/data-analytic...
4,21112009,Breast Cancer Classification,https://www.kaggle.com/niteshyadav3103/breast-...,NaN,Naive Bayes Algorithm in machine learning,NaN,NaN,Breast Cancer Classification,NaN,https://www.askpython.com/python/data-science-...
5,21112009,Global Suicide Indicators,https://www.kaggle.com/datasets/andrewmvd/suic...,NaN,"ML, emotion analysis and detection",NaN,NaN,Detection of Global Suicide Rates,NaN,https://www.mygreatlearning.com/blog/top-data-...
6,21112009,Cornell Car Rental Dataset\n,https://www.kaggle.com/datasets/kushleshkumar/...,NaN,"Visual analysis, statistical and business anal...",NaN,NaN,Car Rentals,NaN,https://www.interviewquery.com/p/data-analytic...
7,21112009,Club Soccer Predictions,https://projects.fivethirtyeight.com/soccer-pr...,NaN,Sports performance analysis,NaN,NaN,Working With the FiveThirtyEight Soccer Data,NaN,https://medium.com/analytics-vidhya/working-wi...
8,21112009,E commerce dataset,https://www.kaggle.com/datasets/carrie1/ecomme...,NaN,Business analytics,NaN,NaN,Customer Segmentation,NaN,https://intellipaat.com/blog/business-analytic...
9,21112009,March Machine Learning Mania 2016achine Learni...,https://www.kaggle.com/c/march-machine-learnin...,NaN,"ML, sports analysis",NaN,NaN,Statistical Analysis in Python using Pandas,NaN,https://medium.com/analytics-vidhya/statistica...
10,21112009,data.csv,https://github.com/vonderwoman/Data-Analysis-w...,NaN,Weather analysis,NaN,NaN,Data-Analysis-with-Python/Weather Data Analysis,NaN,https://github.com/vonderwoman/Data-Analysis-w...
11,21112009,FitBit Fitness Tracker Data,https://www.kaggle.com/datasets/arashnic/fitbit,NaN,"Statistical analysis, health analysis",NaN,NaN,Smart watch data analysis,NaN,https://thecleverprogrammer.com/2022/05/31/sma...
12,21112009,Tinder Dating App - Google Play Store Review,https://www.kaggle.com/datasets/shivkumarganes...,NaN,Sentiment analysis,NaN,NaN,Tinder Reviews Sentiment Analysis,NaN,https://thecleverprogrammer.com/2022/05/24/tin...
13,21112009,India_budget_2021,https://raw.githubusercontent.com/amankharwal/...,NaN,Financial analysis,NaN,NaN,Financial Budget Analysis with Python\n,NaN,https://thecleverprogrammer.com/2021/04/05/fin...
14,21112009,amazon_alexa,https://raw.githubusercontent.com/amankharwal/...,NaN,Sentiment analysis,NaN,NaN,Amazon Alexa Reviews Sentiment Analysis using ...,NaN,https://thecleverprogrammer.com/2021/06/12/ama...
15,21112009,"AAPL,\nMSFT ,INTC, GOOG ,AMZN",https://www.google.com/finance/,NaN,Stock analysis,NaN,NaN,Python for stock analysis,NaN,https://medium.com/analytics-vidhya/python-for...
16,21112009,IPL Complete Dataset (2008-2020)\n,https://www.kaggle.com/datasets/patrickb1912/i...,NaN,Sports performance analysis,NaN,NaN,IPL Data Analysis and Visualization Project us...,NaN,https://machinelearningknowledge.ai/ipl-data-a...
17,21112009,Netflix Dataset,https://drive.google.com/file/d/1p630pDcSkbQp_...,NaN,Sentiment analysis,NaN,NaN,Netflix Data Analysis Project using Python,NaN,https://www.nomidl.com/machine-learning/netfli...
18,21112009,Zomato.csv,https://drive.google.com/file/d/1DAIcR0kEQw2jx...,NaN,Cost analysis,NaN,NaN,Zomato Data Analysis Project using Python,NaN,https://www.nomidl.com/python/zomato-data-anal...
19,21112009,Sales_data.csv,https://drive.google.com/file/d/1dl6mEFIFuzYX7...,NaN,Sale and price analysis,NaN,NaN,Sales Analysis Project using Python,NaN,https://www.nomidl.com/python/sales-analysis-p...

In [23]:
df = df.sort_values(by=['Analyst Register Number'], ascending = True)

In [24]:
df.reset_index(inplace = True, drop = True)

In [25]:
df

,Analyst Register Number,Dataset,DS_Link,Type,Focus,Date,Project_Title,Project Title,Project_Source,Project Source
0,21112009,Sales_data.csv,https://drive.google.com/file/d/1dl6mEFIFuzYX7...,NaN,Sale and price analysis,NaN,NaN,Sales Analysis Project using Python,NaN,https://www.nomidl.com/python/sales-analysis-p...
1,21112009,Diamonds,https://www.kaggle.com/datasets/shivam2503/dia...,NaN,"ML, financial analysis, price analysis",NaN,NaN,Diamond Price Analysis,NaN,https://thecleverprogrammer.com/2022/09/26/dia...
2,21112009,water_potability.csv,https://raw.githubusercontent.com/amankharwal/...,NaN,"Prediction, relationship, ML model",NaN,NaN,Water Quality Analysis,NaN,https://thecleverprogrammer.com/2021/08/19/wat...
3,21112009,Median Weekly Earnings by Sex,https://data.world/bls/median-weekly-earnings-...,NaN,Financial analysis,NaN,NaN,Gender Pay Gap Analysis,NaN,https://www.interviewquery.com/p/data-analytic...
4,21112009,Uber Pickups in New York City\n,https://www.kaggle.com/datasets/fivethirtyeigh...,NaN,Visual analysis,NaN,NaN,Uber Trip Analysis,NaN,https://www.interviewquery.com/p/data-analytic...
5,21112009,Breast Cancer Classification,https://www.kaggle.com/niteshyadav3103/breast-...,NaN,Naive Bayes Algorithm in machine learning,NaN,NaN,Breast Cancer Classification,NaN,https://www.askpython.com/python/data-science-...
6,21112009,Global Suicide Indicators,https://www.kaggle.com/datasets/andrewmvd/suic...,NaN,"ML, emotion analysis and detection",NaN,NaN,Detection of Global Suicide Rates,NaN,https://www.mygreatlearning.com/blog/top-data-...
7,21112009,Club Soccer Predictions,https://projects.fivethirtyeight.com/soccer-pr...,NaN,Sports performance analysis,NaN,NaN,Working With the FiveThirtyEight Soccer Data,NaN,https://medium.com/analytics-vidhya/working-wi...
8,21112009,E commerce dataset,https://www.kaggle.com/datasets/carrie1/ecomme...,NaN,Business analytics,NaN,NaN,Customer Segmentation,NaN,https://intellipaat.com/blog/business-analytic...
9,21112009,Cornell Car Rental Dataset\n,https://www.kaggle.com/datasets/kushleshkumar/...,NaN,"Visual analysis, statistical and business anal...",NaN,NaN,Car Rentals,NaN,https://www.interviewquery.com/p/data-analytic...
10,21112009,data.csv,https://github.com/vonderwoman/Data-Analysis-w...,NaN,Weather analysis,NaN,NaN,Data-Analysis-with-Python/Weather Data Analysis,NaN,https://github.com/vonderwoman/Data-Analysis-w...
11,21112009,FitBit Fitness Tracker Data,https://www.kaggle.com/datasets/arashnic/fitbit,NaN,"Statistical analysis, health analysis",NaN,NaN,Smart watch data analysis,NaN,https://thecleverprogrammer.com/2022/05/31/sma...
12,21112009,Tinder Dating App - Google Play Store Review,https://www.kaggle.com/datasets/shivkumarganes...,NaN,Sentiment analysis,NaN,NaN,Tinder Reviews Sentiment Analysis,NaN,https://thecleverprogrammer.com/2022/05/24/tin...
13,21112009,India_budget_2021,https://raw.githubusercontent.com/amankharwal/...,NaN,Financial analysis,NaN,NaN,Financial Budget Analysis with Python\n,NaN,https://thecleverprogrammer.com/2021/04/05/fin...
14,21112009,amazon_alexa,https://raw.githubusercontent.com/amankharwal/...,NaN,Sentiment analysis,NaN,NaN,Amazon Alexa Reviews Sentiment Analysis using ...,NaN,https://thecleverprogrammer.com/2021/06/12/ama...
15,21112009,"AAPL,\nMSFT ,INTC, GOOG ,AMZN",https://www.google.com/finance/,NaN,Stock analysis,NaN,NaN,Python for stock analysis,NaN,https://medium.com/analytics-vidhya/python-for...
16,21112009,IPL Complete Dataset (2008-2020)\n,https://www.kaggle.com/datasets/patrickb1912/i...,NaN,Sports performance analysis,NaN,NaN,IPL Data Analysis and Visualization Project us...,NaN,https://machinelearningknowledge.ai/ipl-data-a...
17,21112009,Netflix Dataset,https://drive.google.com/file/d/1p630pDcSkbQp_...,NaN,Sentiment analysis,NaN,NaN,Netflix Data Analysis Project using Python,NaN,https://www.nomidl.com/machine-learning/netfli...
18,21112009,March Machine Learning Mania 2016achine Learni...,https://www.kaggle.com/c/march-machine-learnin...,NaN,"ML, sports analysis",NaN,NaN,Statistical Analysis in Python using Pandas,NaN,https://medium.com/analytics-vidhya/statistica...
19,21112009,Zomato.csv,https://drive.google.com/file/d/1DAIcR0kEQw2jx...,NaN,Cost analysis,NaN,NaN,Zomato Data Analysis Project using Python,NaN,https://www.nomidl.com/python/zomato-data-anal...
20,21112016,IEEE,https://ieeexplore.ieee.org/document/7937930,NaN,"SVDD, Time Series Analysis",NaN,NaN,Anomaly Detection for Trustworthy Services in ...,https://www.researchgate.net/publication/31729...,NaN
21,21112016,IEEE,https://ieeexplore.ieee.org/stamp/stamp.jsp?ar...,NaN,"Clustering, Data Fusion, Comprehensive Analysis",NaN,NaN,Mountaineering Events Using Provable Secure Pr...,https://ieeexplore.ieee.org/stamp/stamp.jsp?ar...,NaN
22,21112016,IEEE,https://ieeexplore.ieee.org/stamp/stamp.jsp?ar...,NaN,"Random Matrix Theory, Time Series Analysis",NaN,NaN,Random Matrix theory Framework in a Non-Gaussi...,https://ieeexplore.ieee.org/stamp/stamp.jsp?ar...,NaN
23,21112016,Traffic Prediction Dataset,https://www.kaggle.com/datasets/fedesoriano/tr...,NaN,"Time Series Analysis, Geographical Analysis",NaN,NaN,Traffic Analysis,https://www.netreo.com/blog/how-to-analyze-net...,NaN
24,21112016,Supply Chain Shipment Pricing,https://data.world/usaid/supply-chain-shipment...,NaN,"Descriptive Analytics, Predictive Analytics, P...",NaN,NaN,Supply Chain Analytics,https://www.netsuite.com/portal/resource/artic...,NaN
25,21112016,Price optimization for e-commerce: a case study,https://tryolabs.com/blog/2020/06/01/price-opt...,NaN,"AI, Web Traffic analysis, Campaign Tracking, R...",NaN,NaN,Sales Strategy Optimization,https://www.setsail.co/blog/sales-optimization...,NaN
26,21112016,Breast Cancer Wisconsin (Diagnostic) Data Set,https://www.kaggle.com/datasets/uciml/breast-c...,NaN,"CNN, Classification",NaN,NaN,Breast Cancer Classification,https://www.analyticsvidhya.com/blog/2021/06/b...,NaN
27,21112016,Solar and Lunar Eclipses,https://www.kaggle.com/datasets/nasa/solar-ecl...,NaN,"Time Series Analysis, Pattern Recognition,",NaN,NaN,Solar Eclipse Prediction,https://www.atlasobscura.com/articles/how-to-p...,NaN
28,21112016,Air Quality Data in India (2015 - 2020),https://www.kaggle.com/datasets/rohanrao/air-q...,NaN,"Analytical Chemistry, Liquid Chromatography",NaN,NaN,Pollution Analysis,https://pubmed.ncbi.nlm.nih.gov/9155775/,NaN
29,21112016,Sports Data,https://www.kaggle.com/general/63590,NaN,"Exploration, Visualization, Correlation, Predi...",NaN,NaN,Sports Data Analysis,https://www.youtube.com/watch?v=MpLHMKTolVw,NaN
30,21112016,Suicide Rates Overview 1985 to 2016,https://www.kaggle.com/datasets/russellyates88...,NaN,EDA,NaN,NaN,Detection of Global Suicide Rates,https://medium.com/analytics-vidhya/data-analy...,NaN
31,21112016,Spotify Dataset,https://www.kaggle.com/code/vatsalmavani/music...,NaN,"Content-based filtering, collaborative filteri...",NaN,NaN,Music Recommendation Engine,https://www.music-tomorrow.com/blog/how-spotif...,NaN
32,21112016,Customer Segmentation,https://www.kaggle.com/code/fabiendaniel/custo...,NaN,"Correlation, Clustering, KNN",NaN,NaN,Customer Segmentation,https://www.optimove.com/resources/learning-ce...,NaN
33,21112016,Store Sales,https://www.kaggle.com/competitions/store-sale...,NaN,"Regression, Time Series, Qualitative",NaN,NaN,Forecasting,https://medium.com/@joseph.magiya/introduction...,NaN
34,21112016,Twitter Sentimetn Analysis,https://www.kaggle.com/datasets/jp797498e/twit...,NaN,"NLP, Regex, Text Analysis,",NaN,NaN,Sentiment Analysis,https://www.jigsawacademy.com/blogs/business-a...,NaN
35,21112016,Financial Reporting,https://www.datarails.com/financial-reports/,NaN,"Business Intelligence, Data Wrangling, Visuali...",NaN,NaN,ad hoc reporting,https://www.oracle.com/in/business-analytics/d...,NaN
36,21112016,Wine Quality Dataset,https://www.kaggle.com/datasets/yasserh/wine-q...,NaN,"Random Forest Classifier, Stochastic Gradient ...",NaN,NaN,Wine Quality Prediction,https://www.springboard.com/blog/data-analytic...,NaN
37,21112341,Population,https://datahub.io/core/population,Time series,Change in population from 1960-2018 of a count...,2020.0,None,NaN,NaN,NaN
38,21112341,Bank of England Interest Rates,https://datahub.io/core/interest-rates-gb,Numerical,Interest trends of England from 1694 - 2016,2018.0,None,NaN,NaN,NaN
39,21112341,Population and unemployment,https://github.com/selva86/datasets/blob/maste...,Time series,Population and unemployment trends from 1967 -...,2016.0,None,NaN,NaN,NaN
40,21112341,IBRD Subscriptions and voting power of Member ...,https://finances.worldbank.org/Shareholder-Equ...,Time series,"Total capital subscribed, Total capital paid, ...",2022.0,None,NaN,NaN,NaN
41,21112341,Exchange Rates,https://datahub.io/core/exchange-rates,Time series,Exchange rate trends of different countries fr...,2018.0,None,NaN,NaN,NaN
42,21112341,UK govt bond yiels,https://datahub.io/core/bond-yields-uk-10y,Time series,average yield from british govt. securities fr...,2020.0,None,NaN,NaN,NaN
43,21112341,State - wise socio economic indicators,https://data.opencity.in/dataset/statewise-soc...,Numerical,Best socio economic indicators out of all the ...,2022.0,None,NaN,NaN,NaN
44,21112341,Gross Capital formation (% of GDP),https://data.worldbank.org/indicator/NE.GDI.TO...,Time series,Gross capital formation of different countries,2022.0,None,NaN,NaN,NaN
45,21112341,UK trade in goods,https://www.ons.gov.uk/economy/nationalaccount...,Time series,"Annual, monthly and quartely trade of goods f...",2022.0,None,NaN,NaN,NaN
46,21112341,Output of production industries,https://www.ons.gov.uk/economy/economicoutputa...,Time series,% change in the production output of main indu...,2022.0,None,NaN,NaN,NaN
47,21112341,Unemployment in India,https://www.kaggle.com/datasets/gokulrajkmv/un...,Time series,How unemployment rate increased during Covid 19,2021.0,None,NaN,NaN,NaN
48,21112341,US local area unemp. Statistics,https://catalog.data.gov/dataset/local-area-un...,Time series,Employment and unemployment rate 1976 - 2022 i...,2022.0,None,NaN,NaN,NaN
49,21112341,India GDP from 1960-2021,https://www.macrotrends.net/countries/IND/indi...,Time series,Comparision of growth and annual percentage of...,2022.0,None,NaN,NaN,NaN
50,21112341,USA Education Budget,https://datahub.io/core/usa-education-budget-a...,Time series,"Budget spent by USA on education, USA Budget e...",2018.0,None,NaN,NaN,NaN
51,21112341,Inflation,https://datahub.io/core/inflation,Time series,Inflationary trend from 1973 - 2016 of a count...,2018.0,None,NaN,NaN,NaN

In [26]:
df.to_csv('CollaboratedDataset.csv')